'use strict';

// Generated from the bundled ciphertext files; no network access is needed.
const DividerSamples = [
  {
    id: 'vigenere1', file: 'samples/vigenere1/ciphertext.txt', n: 3,
    text:
      "YHXPIGCPKKLMJELYEXVSAQWXTSYCLECNWRIXTCXVHXFRHWGAVOYOAKEHMQTAGRHQTTPDTNLMJEOGIGUAKGBTVHXFIGNIJWOKQFLW" +
      "CAROPGRTUBKKNZUAUQUMVHXGNZGNWGRBPGHHTAGFEQWXTWAGNTNSHBEIJYKWSPKTAJILUWXGTUTETVHXZHTNELCNTKRBPEOGRRIR" +
      "HXETPDAGAMJUIQNMJEMGNWGRLJOHVSTPDMJERQUGISNPHBUHTNFVQUKUEBPTAGSBINHHTAGRTOHTURNPAGFTAGSFCLEHOPNAKGMT" +
      "MIGIMXNOWATACTLNEXRAPCYMJEGKGAVWBVHHREGGYXUOGCTNTEITIVMSMJEFCNWVHXKRAGAKVEGIAZGSMJEGREHRLXNOGITHIOHP" +
      "PBNGKKMTIELCNWRAEOEKULHPGMQSXGKMJELVRTPGXTSMTAGFSHHFTTOYHSTKNMUHTNLHYEWKNLWNWTYECNWUAGFSIGCBCLEAFKQM" +
      "XXEKASAKRXUEGFOYGNZNAGFDHYNMQCTPTXTBNTYMJERYEGFTHUEXMTAGHHNYUNILUFNNMTTTRTQNKCDVOZKVXJILJEERTHVHXOWA" +
      "GNMJERYEKGSBEK"
  },
  {
    id: 'vigenere2', file: 'samples/vigenere2/ciphertext.txt', n: 4,
    text:
      "QCWBDQQBPOPNDSXOYMGKCGCQZCWBQOVRPFULCCWQSHHYCHJYYHJSDQQXEWPOYHCXPKPKEWQXNCPMPWXOOWPVTPGBEMCXORGNTQCD" +
      "PRVYEVGZCCRYDWVSZBVRLHCVWAGXLFGMCSCDPRGAFONXZKYOLFGOYUCQPRKXLUTOLHESGWNGLFVODHKXRKJOEVGBEVCDYOVSZBQB" +
      "LBAXLHKYYGQMZBEOTJGNLBFCZRGNTQCDPREKYZQXRSPNFFGGPOTOXSVYYOIBPOVLLHVVPTKOWRQPEVCDHOTGPVCFPQQWPHQNPRKM" +
      "LHGKACTDTCPYQHJKETKOWRCCLTKXLZTODHKXRDNKNSHYCHJYDSYRZVGBPUCFPHJOTFNSGSUDSOVDSOVXLHKYYAKQSHNSGSKDTGCV" +
      "ECIOEVGBQWVDTBIKYRRBZDGBEVCDHSURZINNOCVRTGDEEWPKWOTQPFUOYGGGPQCXYCVNPRKMLHGGPQCXYCVMZBUONFCDPKGMLBQD" +
      "SONVZKVRTGIBZIPNEVGLCOXOXSPVTJKXROPNOSCNHVQCEFWQRZGNSSTOSOXONCPCPQTKESFSETCBLPQFPCWBACQBACYOCHQKORQB" +
      "OSVBLQVDSSYYCZFGTZNVTHVVPBQDPBQBWCPQCSOOXPGBHVCDHSUKJVGBPPWDTHEKYBGFPFHYCUGDHVCDEVGIOWFRPFGSEWUPZFWC" +
      "EVGVTJKXRFCDSSTDZPGNTQCDPRJOCSVYEVGEYTKXTGJOOKQBVKJSNVVRPMYRZTQERVVRPFGRLJGDSIUPLFUYYCDVJOFFLBEOOWVS" +
      "DFCDSSTPZFWCECDOSSTOOSFSNOVOOHQDSSIBPOVDLGMBPACSYWPQMSHYCSWCEVCDQFQWEVGCPVQXZFGNOSCNHSVKVSKXNFGKDSFN" +
      "PJQDTCPDZHJKEQCEDSHYCKJSNVVRPMIKGSVRPZCCETWVWAGKDITOZTFOGCVSZBVRLHYOSSTOSWIRWMTODCNFPHJKEHJODSFOLRUR" +
      "LZNXZHJKGSFSPRKXGOKXEVCDEVKCYOVSZBWXOSTQZRURLZNRLJGKYSYLTFVRZTHBPSFYXOPNEVCDRCXOCBOOYHQPEVGZPCRVPPAD" +
      "SSROZDNOQCTDSSROZDNODVCVWBQDASTSDVHBZAVRPSCBEV"
  },
  {
    id: 'vigenere3', file: 'samples/vigenere3/ciphertext.txt', n: 7,
    text:
      "SOZYHJOGAEMWVRDLHLZKMTWDDPGQXNQTBIDDGHEJGBNTLCSFYUSLEHKXVBBSSTCXSWPFQXIHHMOPUPNGZTJKKIQRBQDWIQRHQNDO" +
      "QNSQBIWLNSURTHDODGOEEGTBVYIHHMCQUWEUDWUDTRZLGTOPDLYUDEIIWSOFXDPLNHWBTSRCQQXKEUDOVSDNVTBKDPNGHVCDXSWS" +
      "SWCTOILPQYZTKZIIRIAOTQGGXTKZIVZXCWFFGCDRFZBXOGSDEWQXHSRDVGGPSFZBUSSEUTBISCHHCCYXBIQOOUGTLOLGURTCRFZF" +
      "PDRWSSJYIDDJACNTHHCTGOAVHCMUVTESJOPNHTXAWFGWEWSSTDWESWSCCJRHZTOKZIQROFKXSBNVCSCWRFZFLTWRCHJDWEWCCWLA" +
      "ERQUGDIIQRIRKCDSTQMSCGWSSFKXSLPGYRTNVFRFOCLBLKJSIEULPDSIWLEVRSCKHJSUBPNFWCUOQYKPFVRTRHHOUXDTKTBICDVH" +
      "CMTOBAUVODVTIQEVCDCOUOWFKAIFPHJSCKLEGQFTRBXIERDUWZTVRTWDJHQRTAUEVGBPBETHUKNTRTHUOAFRSRGKGOKOSCBXSKLZ" +
      "NLTLDESYRTNVSSVRDUJSHKDDVHCOHDTRZLFFCXTRNQWBGEGECJOGTKLHURTOXRVVDDHDGSYYCDHCSFKITKTGDEIAWEVGDXMHTHCV" +
      "ASHPAGNFULESPKIUULZDEIWKPBVRTRDMPKDPCWFONVNTRZYCGPTFSCWDDFLEGYKXSWNCCDEOFVSVKCDOZCMOSAWTHCXSTKPBJEGR" +
      "LPRQXPLLNSUDPRWPRVYWEUQSGDUOUTHHVPSKPRCMGOVDVGBBIQOHJKISKPVCNCEYPFDOUOUPGGOCAULPDSIWLEVGSIHHCOYKXSWN" +
      "CCDEOFVSVYGAZLHERIOWLYGYJTRQWVKCDEFFPSCGZTHJMJRLZGKDNSKPFCXPCUZGUDWEITSNNPFWPFKDPNGQCTDJNDESNILAVUIU" +
      "DXNWTAGDDSHPWVZDPGZKPKAAURSTKQBLEVQVTUQOSTDWEKPRIOXNDYCVRTRPZAGXIDRHBYOCTDWWEOPFWPFKDCEYPFQXREFZBUSS" +
      "EUTBIRDWLYHJOLOUWRURTWDDHQQTTRFHCQPIQEVGBPBETHJYAEZPBVCIRDTUJDDNOTYGKIUQYSNPDRVZAGGPYDYRVRTNGTDROSSX" +
      "ORGXAYGZKPCDSXORGXAYWSOVKAIFPVCNCOWLAQWTNWECVRXNNLPQEISWZDRSCGKPFUOAFEPTQBTSKPTQECDKPFUOAFILZNSCGGZK" +
      "PKKEUJRGOEWHWZGSIHHCHJOLEOWKCCKEUJRGOEOUDVGPTLOGSTIHLRHZAPDRVSSJKSPOPBVIDFWTAGKHSKPKGXIDRHBVYAORVODY" +
      "JTKPFCXSTRHCPNTRZSOVGPSJZWPQIOKLDROCNHIHHSGSWDVGDGIHOHQVDONOCYXPNGXOMODUWHVCDHHHHOUMDMLYUVYQUWTHYKHT" +
      "RZRCBZTRDSGKCYWSWPQIHHYGJOAORVSFKITKPGKNTSRQHJOLEOWOPNCOWTQGNIHDEHJONWHCSHSALHOKKDWCXAPQKGDVLBFLDOND" +
      "VGVKEVSSTOPNGEVGBTSKPGCGBASDOPNEIFEITOHHXYUWZDNSPUUCWEWZCMNDWQLXCBURRXCPODFWSSURTLYPGCCHHHAOUCTDLEKC" +
      "CAAEPZNOSOULBIOBAUXONKSEEFHVYWEURFGKIDLDORZDIQEAGXIIWHOUOBPWJGJOSIGYCVVXKHECFBDPWSSLKGFRCTGKGOIVWNVX" +
      "NJDCOOQOGJIPNTRQPOVRHOPLBCQTDWZDWDXTLYHQYCERQHJORUSMCCBSSDDGJOUEOWDCCIIWHSNVIHRFUJDPLLNSVYWEUDSNPPFW" +
      "PFUERHDQONVPSWSWUSHHDWZVRXNNYCVRXNJZTVEBBOTBINDWQDHCSGSKZKDBPVHEVGIALDWZVRXNNXSCDWOPPKJIXWRFZFXISDJO" +
      "PIIHLYUCLDUWTHGFTNLQWHOALRQTVRTTRACHDWEKZIUOLHLNVYKHVHCMNSZEOJHTETDRHBFYLNGZKPGDUOOHJOUAOWBGFTRFZAGD" +
      "DAQPBFSLOQOSTRDWPLBAWXLHDWXOUAOWSPLNTKTGVSBEVSSUKXDDWCWNXMXDHDOVEWEWPQHOPPKJOGEQPOTDWEFPBVBTOIEVGOPR" +
      "WSZGDBEVPSVRPTZZINNQEIZITDWOXDOPNBIOPGFYLNLEVKXZFRCMQEHEHLZKMTHDOZGKGNWDSXOGAOEVKXVSRQHJSHSRCHKXWEUW" +
      "SUCDNVTBVRTSFSCQVGORXOPNIHRFUJDWIVHOUXDTDGSTIVOROCRZDRWFBKDNFRCGJYLIQRCHPWEUVBQGAEGRSCCIHHCSYKHNRZBG" +
      "DDLLDHGXIOKPFUDXLOTHYKHGRZRRBPCWTQGDDSDJWVYKEUJSUDWAWDODYJTWSSTSVHWOWUDPNFPPWDIHHYWYYCDHCKJKILDEWVES" +
      "ERCZQXVIWFRGSKEJZHVYPLLNSJKSNRTRGKLHDEZCDXTXOSYKHOUWCPQXTXOSGSIHHCPWDIHRFUJDIHHJKGBTNLNSIBPNGHCTNHTR" +
      "DOAZGEVPBVVNSKPPGQPNDROKXXWRYRGBXFLDVCVAFDWZTSVHWEVTYJGKEVGOPRWSVQGUUQYMKDALVPSODDCRXSQEIAPZBIDWESPC" +
      "RVTTKLHYKAKZTHJDWELCVGKSSGZKPGPRGEVGKCTLAOVRXEVTHJSCKVSSYKHRDEVGBVLDOHJOGEZLGPYDNHWWUDTNLYUVRXSWTAGK" +
      "HIWOWFXISRFBFKIAOWHJOGIJSHYYGDEFHKCWAOWVCFTTRLGMDWEPHVCDIHHYOOODFWSSEYJNWCMKCNOXVBQGELHLGGWPAPTGVRXS" +
      "QPKBOPLDYRQBPUVEFCVXADYRURTTUTSFDDCXCHUONAVDVGCEONPTCXRYFFFVCTYLYUCCNOXCSHKALLYUVRGOXRVVRTALCRQIDUWS" +
      "WPUNOXNCWVSMDYOIOXTDYRYRPTDYWIXDRDYHNSITOPUKBASKPZNDWIQVAGPDRDDYKXVNRTHNVCEYPFFYIODDYROGHDAGKCWAOWGG" +
      "OXTZCWVDTNXAGQWTWKPFGNDWQOCYXSOZYHJOGEZLGPYIHLYUGVHEWZRQCDAOTQGCDOQMSIKCTDWYKXVAJLWPNXNDSZNWXSVXSXOG" +
      "YPFQJDDNLRVVSHHRFZFDWIQVRKXPHZLGVRTCDEWJYEEWSSAVARHXSOLTRKPFUKJCHCCHWXLNLHVOPTLXSFSCAKXMFOPRLHWURNOX" +
      "HSTOSOZYVGBTWLEVOOIHHCSCBTNRXWEOXNWSSCSGIPLTTKXDEFHAYJMLRVVMPTFSODKIAQOHJKISYPFAVXKHLAQEHEBZIMXDWEFH" +
      "FYRAWDSCDQAWDWYYCDHCOPNWEUPONSREEPUCXIOJPHTKIHHCGNOTPBLBFGTNWZBUKNIQRHQRTRVPZHSCAGCSCWNSRCHQPLABOCEK" +
      "ISHLHDKISGZQCDHEDEPCDHAQOGQWTTLXSUNDBDEGGKICDEGHYGYRFGGOPSVSSEYJLGYHCXHWHCSKDWEUBIGCIIRYWVNXDQEAWMWM" +
      "DEHGBLHLNVYKNSKPDWDXTVSSHOATWSOVCWEZLGFYOIQRCHPPNGSOFTJSWMSIECTROFGKBTKLHURTWDDKCVZIQRVCXSIQSOPNLIWS" +
      "RKXPHDYRUKNIQRHQRTRYPFAOPRQPGVVNNRHRKXPHWPZNWTTKPHTEIHGTRAYJEYPFGKIAELHYRTNVFRFOCLBEVWWETKFARNDWQDVG" +
      "MPMHFDQXPHHLDQPHTLNYUKCDGCMNOPVHDOPNIHHQONVLAVZJGBPLLNSYKHNREODSIHXCHCXSSKPXWWEEGFDQXIOKPFHOTTLYOOYB" +
      "EQEGJOAORVSFEEBXEWVGPSDWZFKGKRGSTRTAGMSHYGEKPFYKHAQZHJOGLRYURKHSDRSCXSTKPKJSIEULPDSIWDDGVSALLYGKQWTK" +
      "FFTIXNJOCYXXTWSSTOLAVYCVKBOPPBVDDBHWCUDPWDJKGXIAOTQGVXKHEVGGXNGLBFGPSMFGVSCTLXSVYWEDCWVCPYDDWVDJRQPR" +
      "CMDRQPFQRBYHLFUKCDZSWUUTRVSCYVPTHTHUQTTWTBICWEZLGEVDSHMSJSCDLEKJOCSKPHWBCEGEVGMDRQPFDEITKPFCLQIWHOUX" +
      "DLRYUGBIOEPGGOCSKPTQECDKPFUOAFLYONYCGOZKJKALZSWERLAVWWVEEBBLFQGDFOLARCWAQRWPQURRXHJOGORQHJOGEZPFGNDO" +
      "UDONVGOXYRVRTHDWZDEITKPMYOGEDWZNYRKHOOPNLHHYONSREKLRDOTNDWZVRTWDJRQGCOQPGKNTAQOIRDWEREVGBIRBTBIOKEUJ" +
      "RQYGSKPKCVZEGDOFVNDRHBVRTMLORNOLOQOSTSCGKZKURTWDDSXOGTRRSVYJTDROKXHUGOSPVNSKPQCWTUSZBCVXTWWSVRGEHWSI" +
      "QTDWLPNOPLOXOFODFVZZKNVLDDGVRTRHHOUXDTKTBIYCIWPLEOETDEWPIVOOOSPUTYDYRCVXCHDTKBHTWSCWQWTZLGVRPTLEAKQW" +
      "TEPZQXVTRZBGYUTKPRQYGSRQHJOWAOWPWDPLDDSKDWEUEVGVDCNDKGBTTRZZCBVERCHJOZEBHOUDDOVXONVQUWLHCXNRDESKDLOX" +
      "WRPYIOSPBCXNOIEVGWWOZPJGBDNWSSUOROQOHKWTRRFBFCWEFLAGEEOQLZQGRUUEOKXHHHSOFXDTQZHKMTDEPTQBTAQOPGRXNGTH" +
      "YKHAOTHVVTDRZFCLDUWQWHDTEQTBERTSKTUJCWEWCWGNIHHWWVDAEJZZFOCKHJWPDWEOZQMKCDWZVGBVRHLHFOAIJSHKDUIWESFK" +
      "AIFPCROCEGEVGNDOULBFPDUQOHJKIIWWSFSCTRLGOKALSLGUKVEQZHOERHOLFIOGTKLBCBPTKZZGCWENYSNDSOZYOPNAORVSFKAO" +
      "QRHJOEAVDOIOXNWZHJOAOYPZKOHTJLFFOCYRFSXOGSDHVQGHHHWCPQTDWZUGDDUWZTVRPTGLFMRPLOLBFGPNGPFCLDUWLAQXVTKZ" +
      "GGLTDVZTDBXGKETNYLEUDOPNIHRDSEYDLIZIPDPIQDPWDHHHNCWVSNRESXOCGHEVGBWEDOHJBDUJSHJOSORCKCIPNGPJGXXFPJVG" +
      "KSWRFZFQDTKCCWQWTKZIIRIPRZFCVXCHTHYYJLGMSQPKEUJZKDILHFGGGXTKZIVWNSKZINNTRVZVJYLIZTGJSROXWRURJTXAZKUT" +
      "AWPZGCROSPWVRXNNTQQEADLQWQXAYNYSYRDWWZPGQXNIZFAYJSHPGQWPNBZIVYUTKPKCIIHLYUURPDKLDROCEGWOVOAYWSOVKAIF" +
      "PVCNQEJFBVYIHLYYVRPTYPFAPTWWSWPQHIQOSGNLEUPFGKALBTARYHSLMZGDWEUPGGOBEGECDOCOXDSKXLALEWPQQYWSSNSITOPR" +
      "QYGSRDVGGTNWMOEUIOWSSVKQLHSONPWOSTBICWEPTUJDUIQOOPYIHHCYGIDNLECTKIAQJFCDTAEZCMYURXWSUPDRVSIVDXNJASQZ" +
      "AEXAZKUTTHWSUMDPHDHJSHTLXSURTFRFBFKAIWEZGLDTWWSQXXTZSWERREUEOKXAYZLGPYIHHCSDOUOUPGCSSAOTQGKCDUZIPNIH" +
      "HYSEUDFWSSDYITOPKCCPPDASTVPBHWKKDWTKPKQBSSGCWPUBEEPOWDXFXWZAZGIQESFYCIWTBNKGGHWSVDTRVTHYKHAOWJGBNWHW" +
      "ZVYHABOFKXZMHMIVDWEZTGGVXTWWSCVXCHHOUXDTJZWPQIOGZHJKIIQLVWBGYQZWNVAORVTKBHTVSSUKXDDYRUOTWKPHJOGIWDAC" +
      "BZEGACKCDNRCBQDUOUDVGRPDUPOFCTVHCONXXCHWWVDAEKTGVYGIHDODYJTFSWNNGEQHVQRPDJZHDEGNWLBFOPTHYIRLNWLWRDOP" +
      "SWDOPNDTKPFWXELHLGCXITKTBICPLOMSEKJSHEVGILOXWRPYIRHXSOLTRWSSUSBPOPFWVTSWSSKBURLPBFCWAGEOWQWTWSSOCJCK" +
      "LGVRPTDCSFRDTSZYGBLIOWPWBCYRFWHIDUKZZFSITRZZQXVAQOHJKIIIJCWMJTBZITPXNJPFXOGYGPSRVNWLEVCUCIIPWVEHUDWZ" +
      "ALAEHOGCXSSKPVCNCEYPFHYGGREHGXIHDEWHIDUGCWPUBUFSTTYBAEZHVVTMDCYGNEOLDCPSIIVLZOYHTFPFVKXNWZRKCPGUPSYS" +
      "IHBZIUYDNHCCTVPTHCVQGTVHCHJSHBREHNOLAVYCVWPRNPRRYXSRYGQKAIFPJGXIUUPRVYIAVESKDPNGQWPNXNJTHXOGYQTQGSIH" +
      "DOWPPPCWLGQBIOIXWZOSFOLJQEGOINVGBGYWLFVMJSWLFFZXNHLDRVTRRLGVDJRNPMVYUFHPOPNWOWMIVDTRHOHQKHTVSSXOGYVZ" +
      "CPPXNLDVGNXTRQTYRPTDNITSDUVQSGVXNJDOKNPLLNSKWJSWMSURJTWTBIEELLVSCDTLHDQQZTAQOGQSIWDDWPNTEGDVGGPSQZKQ" +
      "XAYWPBKXRHHDVKQWAQOVGBUAFPPTSVHWPBGNJPDEHJOIHRFUJDIHDEGJOLAVYCYDWEUTUJDHICPTQBVOLYUVRGOXRVVRTLLEHNOS" +
      "ORCWPDDTKLHNYKEOJUCBSEQQWTCIHRHSXOGSKPKCSIEGQCTKUEZXWPEIEVECUOTIIDVGGPSJZWPQIOVSFKXZAQJTWBIHHCGJOUEO" +
      "EONSITOPBGBKOXDODYJTWSWUPDRLEAKQWTHYRAYJKQZKUKXDDWWEOIOKPFUOAFLYAAQDIQRCWDPLWZUGDWEUWWMOPCDYRNOXWRYR" +
      "GBLHDEWURDUOOPGVXKHEVGXPNGDVGDGIHOHQPPNFJKJKITKPTNKBERQOEKCDOPWUVXKHLTVOGTKPQCXSLHTGDVDWQZIVPDRVSSEY" +
      "JLGYCVBTMHXPGBTVHCVCFXNJDSGXHUFSOVRXNJLTVOGAZSWNOUIQOWPQIHDEBQDWIQRAQBTHDADGXTDVSSFORIGPRQXVOLYUKXIO" +
      "WSSIKGDHYOVYCCHMIVKAAVQCTZDOULZKMTWKPBURTGREHQDWEGZCTCWEIZIPNHHHSOFPDRJZHVOCTKPZKDILHRCNNTNNPMCXSWKP" +
      "BURTWHYHDKRKWZHJOIAEWSHYGIWDVGPDUQOGJOROXWRPYIPRDGKLAYUPOERXTVSSEYJLGDSGSIQXTHGZAALYZADWRRFUJDWEJWOU" +
      "CPNGDVGDGIHOVGBQEVEHQMAIPMIRYCERQHJOAEJDCHDWEWLPNOQUWTHYKHTRZGNSEPHCMCXSWKPBURTHDOHKBTDKPFUOAFRFHYSI" +
      "HWCMKXVTKPDQYGLLEHNOIHLYUUKIDRHBCXSCUTSFMDMHEVGBTSQZIUOXNFCMKXVLLVSVRPTVLWFKAIFPHQRTRVPZHBPTKPFURPRS" +
      "WMKKSVLDSAYJTRWSCFTOIQHJSHMLYIVOHHHRSPOGAOWMIKKEKPFUOAFYPFAQDOGLRXSREWSCWQWSKPJGBNSHWRQWUOOWCYOSIWLB" +
      "FCDMHEWOOHSKPGEYADHOVGBHEOQGQCTVHCSNIPSWZPTSCGWPOTCXNWZVGBTYHDOPNDNFPGJOGEPPADOGEGEFASCGWZPQHWEUZKPO" +
      "PRVQCTRPVLYUERTAWPRJOGSHWTKXPGDXSQPRRRBIGDHHHHOUZAABTBIKVALYGVRTRVPZHPDRWSWUMJRLZIUMWIOOKCCKEUJTQXSO" +
      "IAFGDTNGTBIDDBHEKQZTOSWSDEIIWDBQEHEQZKVRDUJSHRYDRDWWEOIOSCSVOCDWZPGDLOSPCRVTWKJHJOGEVSOTNAYHYCWQWOIX" +
      "SNOUTWZACUTOQPFGCEEFEODVTPHCGQXHORYVGBTYHQSNVDNDWWVDAEJWOUCQOAEVCDLAVWMKXVUQOSTDWEWLPNOHHHZDGXTDLEOP" +
      "NUOXYRKXXTDGSTIHMDWZEKZERYKJSRHWSSYYGDVPOVWTWHCSDOPUWTTWVAYPLFMOSIQNITBPNWDKGVAIOWSCDXTVLWFKAIFPOPNX" +
      "FLEACUTSPPUTYLLDCUGBXCDYFGKRHWSSMONAQOWHSIMDVSUWTGUZKUWPLOPFKMPNFCSGZJNGPFVRTDRZFUYTIWSSTGPYLWZIOIIQ" +
      "ECVRTGDCRGXPNGTRQXICDCSYRXCKSORZTNVDVGKIEDWWVDAEETHCXSSDTRCXMIRFGNIIOKPFUOAFZSWERLABHVKMWWDJVQVSIQRV" +
      "GBWAQOCPDWEWZDQPWEUSSCNIOIPSNGWIFSKCIXTZLGIBDWLYUCXSSKPKCCFULESUEGPUTGGNIOITBFDWAWDVGBTMDTBGNIHHDOOO" +
      "HICPHQLTSXCSVRXSJPBGBPLOJVCZEEQDKJOCOQPSCDHCDVSDEIAOTQGRPDJZHUYBUFSWPDDTKPKCIDFHIDGMIIQRBQDWIQRPWDDU" +
      "WZTVRTWDJHJSCGVECJKEPHYHJKIIWDSGWTDTFWVOSUOWOPNHTXAWFPDROTTGDDGRZBKXIHHNCOWDNZLMUYHHHDSVDDWRCYCXSVHC" +
      "MUYDNITBKCWEGZTHDWEFLYG"
  },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = DividerSamples;
}
